####### Generic Constants
POPULATION_SIZE = 20
SURVIVING_RATIO = 0.20
ELITE_SOLUTIONS_NUMBER = 2
SATISFYING_THRESHOLD_FOR_SOLUTIONS = 0.999
MUTATIONS_NUMBER_BY_SOLUTION = 2
INITIAL_CHANCE_FOR_ITEM_TO_BE_SELECTED = 0.5 #TODO utiliser cette cst là

####### Problem-related Constants
GOAL_WEIGHT = 100
MIN_ITEM_WEIGHT = 5
MAX_ITEM_WEIGHT = 20
AVAILABLE_ITEMS_NUMBER = 30
